version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix(DEV-1195):"
    groups:
      docusaurus:
        patterns:
        - "@docusaurus*"
      react:
        patterns:
        - "@mdx-js/react"
        - "react*"
        - "prism-react-renderer"
